version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  django:
    build:
      context: .

    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_HOST: postgres
      DB_NAME: postgres

    ports:
      - "8000:8000"

    links:
      - postgres

    volumes:
      - ./src/:/project/src/
      - ./backups:/backups

    command: /project/bin/uwsgi.sh

  postgres:
    env_file: .env
    image: mdillon/postgis

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
