# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='tags.Tag'),
        ),
    ]
